name: "ng-ui-blobstorage"
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - ngUI/*

pool:
  vmImage: "ubuntu-latest"

variables:
  azureSubscription: "Visual Studio Enterprise (78033352-805c-4acd-af80-f8f95083268d)"
  serviceConnection: "conNet5App"
  uiPath: "ngUI/"
  ngScript: "create-static-website.sh"
  artifact: "ngapp"

stages:
  - stage: "Provision"
    jobs:
      - job: "Provision"
        displayName: "Provision Static WebSite"

        steps:
          - task: AzureCLI@2
            displayName: Azure CLI
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: Deploy/$(ngScript)

  - stage: Build
    jobs:
      - job: Build

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "12.x"
            displayName: "Install Node.js"

          - script: |
              npm install -g @angular/cli
              npm install
              ng build --prod
            displayName: "npm install and build"
            workingDirectory: $(uiPath)

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "ngUI/dist/ngUI"
              ArtifactName: $(artifact)
              publishLocation: "Container"
            displayName: "Publish build"

  - stage: "Deploy"
    pool:
    vmImage: "windows-latest"
    jobs:
      - job: "Deploy"
        displayName: "Deploy App"

        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              artifactName: $(artifact)
              downloadPath: "$(System.DefaultWorkingDirectory)"

          - task: AzureFileCopy@4
            inputs:
              sourcePath: "drop/ngapp/"
              azureSubscription: $(serviceConnection)
              destination: azureBlob
              containerName: "$web"
